
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    shell: /bin/bash

    working_directory: ~/ips-protodesc-code

    steps:
      - checkout

      - run:
          command: |
            sudo apt-get update
            sudo apt-get install curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: run tests
          command: |
            pipenv run make test

      - store_artifacts:
          path: test-results
          destination: test-results

      - store_artifacts:
          path: examples/output
          destination: output
