
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/ips-protodesc-code

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv pytest mypy
            pipenv install 
      - run:
          name: run tests
          command: |
            pipenv run tests
      - store_artifacts:
          path: test-results
          destination: test-results
