
version: 2
jobs:
  python-testing:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/ips-protodesc-code

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: run tests
          command: |
            pipenv run make typecheck unittests examples/output/draft-mcquistin-augmented-ascii-diagrams/rust examples/output/draft-mcquistin-quic-augmented-diagrams/rust
      - store_artifacts:
          path: test-results
          destination: test-results

      - persist_to_workspace:
          root: examples
          paths:
            - output

  rust-testing:
    docker:
      - image: circleci/rust:1.45-buster

    working_directory: ~/ips-protodesc-code

    steps:
      - checkout

      - attach_workspace:
          at: examples

      - run:
          name: run tests
          command: |
            make integrationtests

workflows:
  version: 2
  testing:
    jobs:
      - python-testing
      - rust-testing:
          requires:
            - python-testing
