
version: 2
jobs:
  python-testing:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/ips-protodesc-code

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: run tests
          command: |
            pipenv run make typecheck unittests examples/output/draft/draft-mcquistin-simple-example/rust examples/simple-protocol-testing/pcaps
      - store_artifacts:
          path: test-results
          destination: test-results

      - persist_to_workspace:
          root: .
          paths:
            - .

  rust-testing:
    docker:
      - image: circleci/rust:1.45-buster

    working_directory: ~/ips-protodesc-code

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: sudo apt-get update
      - run: sudo apt-get install libpcap-dev

      - run:
          name: run tests
          command: |
            make integrationtests

workflows:
  version: 2
  testing:
    jobs:
      - python-testing
      - rust-testing:
          requires:
            - python-testing
